#!/usr/bin/groovy
@Library('github.com/vizuri/openshift-pipeline-templates@master')

def utils = new com.vizuri.openshift.Utils();

def javaBuildPipeline = new com.vizuri.openshift.JavaBuildPipeline();

javaBuildPipeline {
    app_name = 'fhir-base'
    project_folder = 'fhir-base'
}