#!/usr/bin/groovy
  
@Library('github.com/vizuri/openshift-fhir-rules-cicd@master')

def javaDeliveryPipeline = new com.vizuri.openshift.PomBuildPipeline();


javaDeliveryPipeline {
    ocpAppSuffix = 'apps.ocpdemo.kee.vizuri.com'
    imageNamespace = 'admin';
    imageBase = 'quay.apps.ocpdemo.kee.vizuri.com'
    registryUsername = 'admin'
    registryPassword = 'P@ssw0rd'
    app_name = 'fhir-parent'
    ocp_dev_cluster = 'ocpdemo'
    ocp_dev_project = 'demo-fhir-dev'
    ocp_test_cluster = 'ocpdemo'
    ocp_test_project = 'demo-fhir-test'
    ocp_prod_cluster = 'ocpdemo'
    ocp_prod_project = 'demo-fhir-prod'
    project_folder = 'fhir-parent'
}
