#!/usr/bin/groovy
@Library('github.com/vizuri/openshift-pipeline-templates@master')

def utils = new com.vizuri.openshift.Utils();

def pomBuildPipeline = new com.vizuri.openshift.PomBuildPipeline();

pomBuildPipeline {
    app_name = 'fhir-parent'
    project_folder = 'fhir-parent'
}