#FROM fhir/fhir-base-container:latest
FROM fhir/fhir-base:1.0

#ADD target/fhir-patient-service-*.jar /home/jboss/fhir-patient-service.jar
COPY target/fhir-patient-service-*.jar ${APP_ROOT}/fhir-patient-service.jar
#RUN chmod -R 700 ${APP_ROOT}

USER root
RUN chown -R ${USER_UID}:0 ${APP_ROOT} && \
    chmod -R 700 ${APP_ROOT}
USER 10001

ENV JAVA_OPTS=""
ENV APP_JAR=fhir-patient-service.jar
