apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: jenkins
  name: jenkins-jnlp
spec:
  ports:
  - name: agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: jenkins
    namespace: cicd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
