apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: jenkins
    namespace: cicd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
